{{- if .Values.webhook.certManager.generateCaFromCertManager }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "db-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "db-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
    - {{ include "db-operator.fullname" . }}.{{.Release.Namespace }}.svc
    - {{ include "db-operator.fullname" . }}.{{.Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ include "db-operator.fullname" . }}
  secretName: {{ include "db-operator.fullname" . }}
{{- end }}