apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: db-operator-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: db-operator-clusterrole
subjects:
- kind: ServiceAccount
  name: {{ include "db-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
