{{- if .Values.webhook.mutating.enabled }}
{{- $injectCaFrom := printf "%s/%s" .Release.Namespace (include "db-operator.fullname" .) }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: db-operator
  annotations:
    cert-manager.io/inject-ca-from: {{ $injectCaFrom }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "db-operator.fullname" . }}
      namespace: {{ .Release.Namespace }}
      path: /mutate-agill-apps-db-operator-v1alpha1-dbinstance
  failurePolicy: Fail
  name: {{ include "db-operator.fullname" . }}.{{.Release.Namespace }}.svc.cluster.local
  rules:
  - apiGroups:
    - agill.apps.db-operator
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dbinstances
  sideEffects: None
{{- end }}