{{- $root := .Values }}
{{- range $provider := .Values.providers }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ $provider.name }}
  namespace: {{ $provider.namespace }}
type: Opaque
data:
  {{- toYaml $provider.data | nindent 2 }}
{{- end }}