apiVersion: v1
kind: Service
metadata:
  name: {{ include "db-operator.fullname" . }}
  labels:
    {{- include "db-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (or (.Values.webhook.validating.enabled) (.Values.webhook.mutating.enabled)) (.Values.webhook.certManager.generateCaFromCertManager) }}
    - name: https
      port: 443
      targetPort: 9443
    {{- end }}
  selector:
    {{- include "db-operator.selectorLabels" . | nindent 4 }}
