# permissions for end users to edit dbclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dbcluster-editor-role
rules:
- apiGroups:
  - agill.apps.db-operator.agill.apps.db-operator
  resources:
  - dbclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - agill.apps.db-operator.agill.apps.db-operator
  resources:
  - dbclusters/status
  verbs:
  - get
