# permissions for end users to view dbinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dbinstance-viewer-role
rules:
- apiGroups:
  - agill.apps.db-operator.agill.apps.db-operator
  resources:
  - dbinstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - agill.apps.db-operator.agill.apps.db-operator
  resources:
  - dbinstances/status
  verbs:
  - get
