
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - agill.apps.db-operator.agill.apps.db-operator
  resources:
  - dbclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - agill.apps.db-operator.agill.apps.db-operator
  resources:
  - dbclusters/finalizers
  verbs:
  - update
- apiGroups:
  - agill.apps.db-operator.agill.apps.db-operator
  resources:
  - dbclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - agill.apps.db-operator.agill.apps.db-operator
  resources:
  - dbinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - agill.apps.db-operator.agill.apps.db-operator
  resources:
  - dbinstances/finalizers
  verbs:
  - update
- apiGroups:
  - agill.apps.db-operator.agill.apps.db-operator
  resources:
  - dbinstances/status
  verbs:
  - get
  - patch
  - update
