name: main

on: 
  push: 
  pull_request:

jobs:
  update-yaml-in-another-repo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      name: checkout target repo
      with:
          repository: agill17/s3-operator
          path: s3-operator
          token: ${{ secrets.PAT }}
          ref: master-old 
    - name: update chart version
      uses: fjogeleit/yaml-update-action@master
      with:
        valueFile: 'chart/s3-operator/Chart.yaml'
        propertyPath: 'dependencies.0.version'
        value: 2.0.0
        repository: agill17/s3-operator
        # branch: feature/dep-update
        targetBranch: master-old
        createPR: true
        message: 'Update chart Version'
        token: ${{ secrets.PAT }}
        workDir: s3-operator
