name: main

on: 
  push: 
  pull_request:

jobs:
  update-yaml-in-another-repo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      name: checkout target repo
      with:
          repository: agill17/s3-operator
          path: target
          token: ${{ secrets.PAT }}
          ref: master 
    - name: update chart version
      uses: fjogeleit/yaml-update-action@master
      with:
        valueFile: 's3-operator/Chart.yaml'
        propertyPath: 'dependencies.0.version'
        value: 2.0.1
        repository: agill17/s3-operator
        branch: testbranch
        targetBranch: master
        createPR: true
        message: 'Update chart Version'
        token: ${{ secrets.PAT }}
        workDir: target
