name: main

on: 
  push: 
  pull_request:

jobs:
  update-yaml-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update Chart version
      uses: fjogeleit/yaml-update-action@master
      with:
        valueFile: 'db-operator/Chart.yaml'
        propertyPath: 'version'
        value: 1.0.1
        branch: chnage/master
        createPR: 'false'
        message: 'Update chart.yaml' 
    - name: Update values
      uses: fjogeleit/yaml-update-action@master
      with:
        valueFile: 'db-operator/values.yaml'
        propertyPath: 'image.tag'
        value: fooooooo
        branch: chnage/master
        targetBranch: master
        createPR: 'true'
        message: 'Update values.yaml' 
